#!/bin/sh


make && make install

BUILD_PATH=${PWD}

# update conf
cp $BUILD_PATH/conf/jda_nginx.conf /usr/local/nginx/conf/nginx.conf

# update binary
cp -f $BUILD_PATH/objs/nginx /usr/local/nginx/sbin/nginx
